name: Dropbox deploy workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Update and install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq texlive-latex-base

    - name: Install Python packages
      run: pip install dropbox

    - name: Build project
      run: |
        python build.py
        pdflatex resume.tex
        echo "Hello World!"
        echo "var=$test_var"
        echo "env=$test_env"
        echo ${{env.MY_ENV}}
        echo ${{vars.MY_VAR}}
        python deploy.py
