name: Dropbox deploy workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    env:
        PDF_FILE_NAME: "resume.pdf"
        TEX_FILE_NAME: "resume.tex"

    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Update and install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq texlive-latex-base

    - name: Install Python packages
      run: pip install dropbox

    - name: Build PDF file
      run: pdflatex $TEX_FILE_NAME

    - name: Build project
      env:
        DROPBOX_ACCESS_TOKEN: ${{secrets.DROPBOX_OAUTH}}
      run: python3 deploy.py
